language: python

python:
- '3.7'

matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
- eval "${MATRIX_EVAL}"

install:
- sudo apt-get install $CXX
- pip install .[test] --upgrade

script:
- pytest tests/test*.py
